variable "region" {}
variable "vpc_name" {}
variable "certificate_arn" {}
variable "target_port" {}
variable "alb_sg_name" {}
variable "pub_subnet_az1_name" {}
variable "pub_subnet_az2_name" {}
variable "tg_name" {}
variable "tg_protocol" {}
variable "alb_name" {}
variable "instance_name" {}
